## Multi variable LSTM model

We will be working with **Multivariate time series data** which means that the data has more than one feature (input) for each time step

In [21]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

## Dataset

Simple example of two input time series (**X1** and **X2**) where the output series (**y**) is the simple addition of the input series (**y=X1+X2**)

In [18]:
N = 50 # Number of samples
in_1 = [i*10 for i in range(1,N)]
in_2 = [i*10+5 for i in range(1,N)]
out = [in_1[i]+in_2[i] for i in range(len(in_1))]

In [19]:
df = pd.DataFrame()
df["X1"] = in_1
df["X2"] = in_2
df["y"] = out
df.head()

X1  X2    y
0  10  15   25
1  20  25   45
2  30  35   65
3  40  45   85
4  50  55  105

## Made data as 3D

This is the main step where we make our dataset as 3D shape (because LSTM requires it in this way) 

*(number_samples, number_timesteps, number_features)*

Obviously `number_features = 2` here (because **X1, X2** are the 2 input features)

Suppose if `number_timesteps = 3` then, our first sample input will be:

**Input**:

10, 15

20, 25

30, 35

and our output will be (corresponding to last sample):

**Output**:

65

We can define a function named **split_sequences()** that will make the dataset into the form as we have discussed above (through some very simple manipulations)

In this function, the arguement `sequences` denote the entire dataset and `n_steps` denote the **number_timesteps**

In [22]:
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        end_ix = i + n_steps
        if end_ix > len(sequences):
          break
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [23]:
X, y = split_sequences(df.values, 3)

In [24]:
X.shape, y.shape

((47, 3, 2), (47,))

### First sample

In [26]:
X[0], y[0]

(array([[10, 15],
        [20, 25],
        [30, 35]]), 65)

## Split to train and test

Here number of samples is $N=50$

So, we will split train and test as 40 and 10 samples respectively

In [27]:
X_train, y_train = X[:40], y[:40]
X_test, y_test = X[40:], y[40:]

## Training the model

We are now ready to fit an LSTM model on this data

In [28]:
# define model
model = Sequential()

n_steps, n_features = 3, 2

# Each of our sample has input of shape (number_timesteps, number_features) 
# This is provided to the LSTM model via input_shape argument
# Activation function is set as 'relu' and there are 50 nodes in LSTM model

model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))

# Since each sample has an output of shape=1 only (remember first sample output was 65)
# Thus we add a Dense layer with only 1 node 

model.add(Dense(1))

# Our optimizer is "adam" and loss that we use for regression is "mse" (mean square)

model.compile(optimizer='adam', loss='mse')

## Summary of the model parameters

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 50)                10600     
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 10,651
Trainable params: 10,651
Non-trainable params: 0
_________________________________________________________________


## Fit the model

Finally we fit the model on train dataset and predict it on test dataset

In [30]:
model.fit(X_train, y_train, epochs=200, verbose=0)

# Make prediction
We predict the values on test data

In [36]:
yhat = model.predict(X_test, verbose=0)
yhat = yhat.flatten()

## First test sample

In [32]:
X_test[0]

array([[410, 415],
       [420, 425],
       [430, 435]])

In [38]:
y_test[0], yhat[0]

(865, 865.2869)

### So we observe such close prediction!



## Second Test sample

In [39]:
X_test[1]

array([[420, 425],
       [430, 435],
       [440, 445]])

In [40]:
y_test[1], yhat[1]

(885, 885.3503)

### Again the prediction is very close!